### ISSUE TITLE
select count from union subquery with limit doesn't work

### ISSUE THREAD

**Issue by dorinhogea** [bloomberg/comdb2#1030]
$ c 'select c from t2'
(c=1)
(c=2)
$ c 'select f from t3'
(f=6)
$ c 'select c from t2 union all select f from t3'
(c=1)
(c=2)
(c=6)
c 'select count(*) from (select c from t2 union all select f from t3)'
(count(*)=3)
c 'select count(*) from (select c from t2 union all select f from t3 limit 1)'
(count(*)=3)                                        <<<<<<<<<<<<<<<<<<<<<<<<<<
 c 'select count(*) from (select c from t2 union all select f from t3 limit 1 offset 1)'
(count(*)=NULL)                                   <<<<<<<<<<<<<<<<<<<<<<<<<

**Comment by riverszhang89** [comment]
```
mydb> select count(*) from (select 3 union all select 2 limit 1)
(count(*)=2)
mydb> select count(*) from (select 3 union all select 2 limit 1,1)
(count(*)=NULL)
```

**Comment by dorinhogea** [comment]
The generated plan tries to use uninitialized Mem offset/limit integers.  In the optimized form, it gives bad results.  If debug is enabled, a sqlite assert aborts the server.
