### ISSUE TITLE
Reconsider #1036

### ISSUE THREAD

**Issue by akshatsikarwar** [bloomberg/comdb2#1038]
PR #1036
Seems like we were doing the right thing. If we do decide to keep “fix” can we instead scan from end instead of scanning entire string.

**Comment by nirbhayc** [comment]
> Seems like we were doing the right thing

I agree.

> can we instead scan from end instead of scanning entire string.

I tried to do what R6 currently does. I can change it to scan from backwards (or perhaps just check if the last char is null) and decrement the length accordingly. But that would potentially break apps which rely on R6's behavior and have been (erroneously) passing null(s) hidden somewhere around in the middle (passing strlen(str) +10 as len), for which R6 simply wouldn't complain.

**Comment by akshatsikarwar** [comment]
Lets call `strlen` which will at least use SIMD where available instead writing loop to scan for it ourselves. Are we documenting that embedded null will lead to silent truncation?
