### ISSUE TITLE
using from hibernate

### ISSUE THREAD

**Issue by pdeva** [bloomberg/comdb2#144]
can hibernate be used to make calls to comdb?
if so, which hibernate dialect should be used

**Comment by riverszhang89** [comment]
Unfortunately we don't have a comdb2 dialect for hibernate yet. However it is probably okay since comdb2 understands most of the SQL standard. I'd suggest that you pick any hibernate built-in SQL dialect and avoid vendor-specific SQL.

**Comment by aibolit** [comment]
I am having success with https://github.com/gwenn/sqlite-dialect
Gradle dependency: 
```
	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
	dependencies {
	        compile 'com.github.gwenn:sqlite-dialect:-SNAPSHOT'
	}
```

**Comment by riverszhang89** [comment]
@aibolit Thank you for sharing!
