### ISSUE TITLE
adding/removing nodes from cluster

### ISSUE THREAD

**Issue by pdeva** [bloomberg/comdb2#147]
the documentation leaves out a lot of details about this.
when a node is added/removed from a cluster:

1. do i need to update the config of every single other node in the cluster with the updated node's hostname?
2. do all the other nodes need to be rolling restarted to read this new config?
3. does all the client code need to be updated too to add this node's hostname to their driver initialization call?

**Comment by mponomar** [comment]
[Configuring clusters](https://bloomberg.github.io/comdb2/cluster.html)

1.  You need to add the full cluster membership to every instance's config file.   We've toyed with the idea of fetching that information from somewhere else on startup.  It's still a possibility, but this step is very easy to automate.  It's a single line in a config file.

2.  No, nodes can come and go dynamically.

3. [Client setup](https://bloomberg.github.io/comdb2/clients.html).  No, as long as at least one node is reachable and is in the client's configuration, it'll learn about other nodes.  You can also configure a database to contain cluster information, and API code will learn from that.

**Comment by pdeva** [comment]
regarding 2. , i am a little confused.
if a reboot of the node is not needed, when does the database node read the updated config? 
in fact, one would think that if all nodes can come and go dynamically then why is the config needed at all.

**Comment by dorinhogea** [comment]
nodes exchange cluster information

**Comment by mponomar** [comment]
It's needed in case of a reboot.   Membership information is exchanged between nodes when nodes join/leave.

**Comment by dorinhogea** [comment]
in theory it is not require to update all config files, but it is more robust to have the cluster information persisted everywhere

**Comment by dorinhogea** [comment]
"3. does all the client code " : definitely not a code change :)

**Comment by mponomar** [comment]
For what it's worth: I think we documented cluster setup in some detail, eg: [growing a cluster](https://bloomberg.github.io/comdb2/cluster.html#growing-a-cluster).   If you feel like something is missing, we'll gladly update it.

**Comment by pdeva** [comment]
from the docs:

once a new node is brought back up, first the data from another node must be copied to it.
then any updates missed will be caught up.

this might be silly but:
if the node can automatically catch up with all the updates anyway, why even require the initial copying of data. why not just allow adding the node to the cluster and have the cluster take care of populating the node fully. its how cassandra does it.

**Comment by mponomar** [comment]
It's not silly at all.  It's something we thought about as well.  Copying the database is a single command, and it's something we've automated a long time ago.

**Comment by pdeva** [comment]
>If you feel like something is missing, we'll gladly update it.
as i mentioned in this thread, it is unclear if the node requires restarting upon updating the config. this thread makes it all clear, but the docs dont

**Comment by mponomar** [comment]
Fair enough.  It's something we would have mentioned if it were required (it would also be painful to use...), but nothing wrong with clarifying it.
