### ISSUE TITLE
how are comdb2 releases structured?

### ISSUE THREAD

**Issue by pdeva** [bloomberg/comdb2#149]
1. what is the current version number?
2. what is release schedule like?
3. are releases backward compatible?
4. is there a roadmap?

**Comment by mponomar** [comment]
1.   The code you're looking at will eventually get a 7.0.0 tag.
2.   Major changes get a major version number bump - see point 3.
3.  Releases are always forward and backwards compatible to at least 1 major version.
4.  There's no available roadmap.

**Comment by pdeva** [comment]
>The code you're looking at will eventually get a 7.0.0 tag.

is current code in master good enough to deploy in production?

**Comment by mponomar** [comment]
This is not yet the version we're running at Bloomerg.  It's one major release behind, and we're developing it in the open.  I can't really make a risk assessment for you, unfortunately.
