### ISSUE TITLE
incremental backups and point in time recovery

### ISSUE THREAD

**Issue by pdeva** [bloomberg/comdb2#150]
1. Is it possible to do incremental backups? Current docs say that only full backup is allowed, which can be resource consuming as size of data gets larger.
2. Is point in time recovery possible?
3. Does performing backup degrade the performance of the individual node or the entire cluster in any way during the backup?
4. can backup be taken from any node or just the master?

**Comment by mponomar** [comment]
Backups only interact with the database to ask it to hold log files.  The backup program reads the database files directly.  Other than using the database's disk, there's no additional use of database resources.  Backups can be taken on any node.  Partial backups are possible but we don't yet provide a way to take them.  [Recovering to a point in time.](https://bloomberg.github.io/comdb2/args.html#recovertotime) (you'd need to configure your db to keep log files, see config file section).
