### ISSUE TITLE
per connection overhead

### ISSUE THREAD

**Issue by pdeva** [bloomberg/comdb2#151]
postgres is famous for having high per connection penalty. It forks a new process for every connection. 

1. What is the per connection overhead in comdb?
2. Does it too fork a new process per connection or just a thread or something else?
3. Does the 'open file limit' on linux typically need to be modified (using ulimit -n) for production servers with high connection counts.

The documentation lacks any literature about this, so some clarity would be nice

**Comment by mponomar** [comment]
Connections are cheap.  A connection uses a thread and a file descriptor on the database side.  [cdb2sockpool](https://bloomberg.github.io/comdb2/clients.html#cdb2sockpool) allows for client connection pooling.  Connect/run statements/disconnect is a viable model. There's no need to hold onto connections.  'maxappsockslimit' tunable (1400 by default) controls how many connections per node are allowed (check config files section where all tunable are documented).
