### ISSUE TITLE
one time 'code dump' or continuous development

### ISSUE THREAD

**Issue by pdeva** [bloomberg/comdb2#154]
It is unclear what Bloomberg's goal with this project are.

1. Is this just a one time 'code dump' for others in the database community to look at as a 'reference implementation' and incorporate in their own databases?

2. Or do you actually plan to continue active development of Comdb2 in the open here and would like businesses to use it in production?

It the answer is 2., then why not:

1. Put out some roadmap of the project
2. Give some sort of release schedule
3. Add a community forum/google group for discussions

We would very much like to use comdb2 in production, but it is unclear how committed bloomberg is to this open source project, since in #149 you mentioned that bloomberg is already using a much more recent version internally.

Some clarifications would be very nice for everyone looking at this project seriously.

**Comment by mponomar** [comment]
(2) This is the next version of Comdb2 that we're developing openly.  You can see recent commits. Bloomberg is running an older version, not a newer one (i got it backwards in my original response, quickly corrected).

Forums for Comdb2 will be created at some point soon.

I can't really say very much about a roadmap and a release schedule.  Our internal releases consist of us starting a version branch and rolling it out to databases at Bloomberg in phases.  We've stuck with this model for a long time, and we're evolving it now that the database is open.

**Comment by pdeva** [comment]
considering this is the 'new' version, can you possibly give some idea about what is the big highlight of this release compared to the older version running at bloomberg?

also glad to know the answer was option 2. we will be investigating comdb2 a ton more now :)
