### ISSUE TITLE
build frequently broken

### ISSUE THREAD

**Issue by pdeva** [bloomberg/comdb2#218]
guys, we have been considering using this in production.
However, the part that is scary is that the build icon frequently shows some tests failing. Even right now it shows 6 tests failing.

have you thought of a possibility of creating a separate `dev` branch and merge to master only after all tests pass, so people using in prod can just update from 'master'.

given there is no roadmap, release schedule or any indication of what constitutes a stable enough build, how do you recommend any outside org decide to use comdb?

**Comment by dorinhogea** [comment]
A valid point; please bear in mind this is pre-release version, and the build will break frequently.  The plan is to tag the production releases as such and recommend using the latest.  We are still cooking the first production release.

**Comment by pdeva** [comment]
is the production release supposed to happen in weeks, or months or sometime next year?
it would be very helpful to anyone looking at comdb2 to get some idea of this.

**Comment by dorinhogea** [comment]
IIRC, ETA is Q4

**Comment by mponomar** [comment]
@pdeva, we set up a forum at https://discuss.tech.bloomberg/c/comdb2 for Comdb2 discussions.  It's a little empty at the moment, but feel free to post, and we'll answer questions there if you'd like.  Still public and searchable, but it's a better forum to use then github issues.
