### ISSUE TITLE
Failed testcase isn't flagged correctly

### ISSUE THREAD

**Issue by akshatsikarwar** [bloomberg/comdb2#2247]
Run testcase: `make eventlog`:
```
...
check all .*sql entries for fingerprint
Failed output is different from expected
exit -1 
check the sql parameter now
...
```
Looks like this only exits the sub-shell, while test keeps going. Also, I think the test itself is buggy as expected output is incorrect.

**Comment by akshatsikarwar** [comment]
I have fixed this particular instance (https://github.com/bloomberg/comdb2/pull/2235/commits/a80b52359d70bee04d8c7cf2f4b56beddb3567c0) but perhaps we need a larger fix so to catch where ever this construct is used.
Proposal: `failexit` can touch a trap file and test-harness can check for its existence so we don't silently pass any failing tests.

**Comment by akshatsikarwar** [comment]
@adizaimi

**Comment by adizaimi** [comment]
Yes, possibly more tests have same issue -- your suggestion is a good one. Few tests do that already, we can generalize it that way.

**Comment by akshatsikarwar** [comment]
This is fixed. Thank you Adi.
