### ISSUE TITLE
Two undefined behavior problems 

### ISSUE THREAD

**Issue by Jerry-aha** [bloomberg/comdb2#2272]
Two undefined behavior problems are found when fuzzing with comdb2.

## Problem 1
The bug report is:
```sh
/root/workspace/comdb2/sources/db/comdb2.c:5422:33: runtime error: left shift of 3653224 by 16 places cannot be represented in type '__pid_t' (aka 'int')
    #0 0x2b94254 in main /root/workspace/comdb2/sources/db/comdb2.c:5422:33
    #1 0x7fedcd41a001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
    #2 0x711b5d in _start (/root/workspace/comdb2/bin_asan/comdb2.dfuzz-counter,dfuzz-asan-instrument.out+0x711b5d)
```
The code is 
```C
srand(time(NULL) ^ getpid() << 16);
```
The return value type of getpid() is int, and the bit operation of int might overflows, so the behavior is undefined. The compiler may optimize the operation arbitrarily, resulting in random number seed conflict.
According to ISO C99 6.5.7
> The result of E1 << E2 is E1 left-shifted E2 bit positions; vacated bits are filled with zeros. If E1 has an unsigned type, the value of the result is E1 * 2^E2, reduced modulo one more than the maximum value representable in the result type. If E1 has a signed type and nonnegative value, and E1 * 2^E2 is representable in the result type, then that is the resulting value; otherwise, the behavior is undefined.

## Problem 2
The bug report is:
```sh
/root/workspace/comdb2/sources/net/net.c:3023:37: runtime error: signed integer overflow: 3653224 * 65537 cannot be represented in type 'int'
    #0 0x2c513f9 in create_netinfo /root/workspace/comdb2/sources/net/net.c:3023:37
    #1 0x2be1630 in open_bdb_env /root/workspace/comdb2/sources/db/glue.c:3654:33
    #2 0x2b9e43c in init /root/workspace/comdb2/sources/db/comdb2.c:3796:9
    #3 0x2b93abe in main /root/workspace/comdb2/sources/db/comdb2.c:5466:9
    #4 0x7fedcd41a001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
    #5 0x711b5d in _start (/root/workspace/comdb2/bin_asan/comdb2.dfuzz-counter,dfuzz-asan-instrument.out+0x711b5d)
SUMMARY: UndefinedBehaviorSanitizer: signed-integer-overflow
```

The code is 
```C
netinfo_ptr->seqnum = (getpid() * 65537);
```

**Comment by mponomar** [comment]
We don't need this value to be random, or even initialized.   Still probably worth cleaning this up.

**Comment by adizaimi** [comment]
Thank you for the bug report. Much appreciated.
