### ISSUE TITLE
The JDBC driver build is broken. com.bloomberg.comdb2.jdbc.Sqlquery doesnt exist

### ISSUE THREAD

**Issue by dprophet** [bloomberg/comdb2#2330]
**Describe the bug**

git clone master
open the pom.xml in the cdb2jdbc directory with IntelliJ. Then compile the code.

comdb2\cdb2jdbc\src\main\java\com\bloomberg\comdb2\jdbc\Comdb2Handle.java
Error:(28, 1) java: package com.bloomberg.comdb2.jdbc.Sqlquery does not exist

You will see Sqlquery isnt even checked in the repo.

**Comment by riverszhang89** [comment]
`com.bloomberg.comdb2.jdbc.Sqlquery` is generated protobuf code. The protobuf compiler (`protoc`) is required to build the JDBC driver. Pre-built `protoc` binaries can be found [here](https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.3).
