### ISSUE TITLE
Add support for INSERT ON CONFLICT

### ISSUE THREAD

**Issue by pdeva** [bloomberg/comdb2#236]
Postgres since 9.5 added support for `INSERT ON CONFLICT... RETURNING` that allows for easy Upserts.

- [Postgres - whats new](https://wiki.postgresql.org/wiki/What's_new_in_PostgreSQL_9.5#INSERT_..._ON_CONFLICT_DO_NOTHING.2FUPDATE_.28.22UPSERT.22.29)

- [Postgres insert - reference doc](https://www.postgresql.org/docs/current/static/sql-insert.html)

It would be great to have similar feature in Comdb considering how common the use of upserts is.

**Comment by pdeva** [comment]
as added ref, link to slides + talk of postgre's upsert design:
https://speakerdeck.com/peterg/upsert-in-postgresql

**Comment by akshatsikarwar** [comment]
This will indeed be useful to have and has been requested internally many many times. However, it's a bit difficult to pull off in an OCC system. We have a few plans and most likely implementation can be prioritized after we make first stable release.

**Comment by alexscotti** [comment]
+1 FOR UPSERT

**Comment by pdeva** [comment]
one big flaw with postgre's upsert design is it doesnt have any way to return if a row was inserted or updated. that is a vital piece of info. There are lots of hack on stackoverflow that use postgre's internals to return that info.

i believe's comdb's upsert design should take this feature into consideration as you guys design yours

**Comment by nirbhayc** [comment]
Good point. Once implemented, [cdb2_get_effects](https://bloomberg.github.io/comdb2/c_api.html#cdb2_get_effects) should have those details.

**Comment by pdeva** [comment]
well if one has to call `cdb2_get_effects` separately thats a whole new network call.
The whole point of upsert as a statement is that you can do all the work in a single call.
I mean one can do upsert today by using transaction and making multiple sql calls (selectv followed by insert).
having a separate call, that too non-sql, to get the results defeats the whole purpose.

**Comment by alexscotti** [comment]
can we expose the results of get_effects through SQL?

**Comment by mponomar** [comment]
cdb2_get_effects won't make a round trip to the database, if that's what you mean by "network call".  Calling it is basically getting you additional information, much like looking at the return code for cdb2_run_statement (that's non-SQL also).

**Comment by pdeva** [comment]
i see. but doesnt that leave room for race conditions.
2 threads may be making a transaction at the same time and may get each other's results on call to cdb2_get_effects.

**Comment by mponomar** [comment]
2 threads [can't share the same connection](https://bloomberg.github.io/comdb2/c_api.html#a-word-on-thread-safety), so no.  Connections are cheap - get one per thread.

**Comment by pdeva** [comment]
Regarding `cdb2_get_effects`.

It seems that it doesnt actually solve the problem. When more than one row is inserted or updated, it wont tell you exactly which of those rows were inserted and which were updated. It just tells you the total coutns of each.

Note that there is no documentation for `cdb2_effects_tp`, so we don't even know what this method returns

**Comment by akshatsikarwar** [comment]
This work was done: https://bloomberg.github.io/comdb2/sql.html#insertreplace
