### ISSUE TITLE
Consistent test case logging

### ISSUE THREAD

**Issue by danshearer** [bloomberg/comdb2#2403]
**The results of test cases are inconsistently logged**

If you run the command:

```
find . -name \*.testcase -print  | xargs tail -n 3
```
then there are almost no identical formats. Success or Failure are recorded in many different ways, or sometimes not at all.

**Describe the solution you'd like**

A standard format such as:

Success: optional parameter(s)
Duration: NNNN seconds

Fail: optional parameter(s)
Duration: NNNN seconds

**Describe alternatives you've considered**

Giving up parsing what is going on :-)

**Additional context**

Here is partial output of the above command:

==> ./tests/test_66869/logs/scasyncconstraintslogicalscgenerated66869.testcase <==
10:26:56> Completed 10 rebuilds
10:26:56> Success
Duration 540 seconds

==> ./tests/test_66869/logs/unionparmaxqueue66869.testcase <==
13:35:54> Limited queue size 1999800
13:35:54> Testcase passed.
Duration 179 seconds

==> ./tests/test_66869/logs/sirace66869.testcase <==
11:40:01> + echo 'Success!'
11:40:01> Success!
Duration 320 seconds

==> ./tests/test_66869/logs/queuedbrollovernoroll1generated66869.testcase <==
11:34:36> + echo SUCCESS
11:34:36> SUCCESS
Duration 1940 seconds

==> ./tests/test_66869/logs/truncatesc66869.testcase <==
12:13:57> [assert_notable] Assert t2 does not exist
12:14:02> [assert_notable] Assert t3 does not exist
Duration 1773 seconds

==> ./tests/test_66869/logs/systablelockingextralockgenerated66869.testcase <==
13:51:57> Completed 40 write_tables
13:52:28> Completed 60 stat_all_tables
Duration 2049 seconds

==> ./tests/test_66869/logs/socksqlmasterswings66869.testcase <==
12:51:19> ./runit: line 122: 603783 Killed                  ./downgrade.sh $dbname > downgrade.log 2>&1
12:51:19> Testcase passed.
Duration 450 seconds

==> ./tests/test_66869/logs/systablelocking66869.testcase <==
13:44:24> Completed 70 stat_all_tables
13:44:38> Success
Duration 515 seconds

==> ./tests/test_66869/logs/maxtable66869.testcase <==
13:19:36> [rebuild t254] rc 0
13:19:36> [commit] rc 0
Duration 1691 seconds

==> ./tests/test_66869/logs/queuedbrollover66869.testcase <==
11:02:15> + echo SUCCESS
11:02:15> SUCCESS
Duration 2128 seconds

==> ./tests/test_66869/logs/incrementalbackupload66869.testcase <==
13:33:02> Test Successful
13:33:02> + exit 0
Duration 812 seconds

==> ./tests/test_66869/logs/cldeadlock66869.testcase <==
11:44:35> ./runit: line 176: 406869 Killed                  coherent_loop $max_incoherent
11:44:35> Success
Duration 273 seconds

==> ./tests/test_66869/logs/truncatescofflinegenerated66869.testcase <==
12:43:42> [assert_notable] Assert t2 does not exist
12:43:47> [assert_notable] Assert t3 does not exist
Duration 1784 seconds

==> ./tests/test_62510/logs/socksqlmasterswings62510.testcase <==
13:48:54> ./runit: line 122: 88768 Killed                  ./downgrade.sh $dbname > downgrade.log 2>&1
13:48:54> Testcase passed.
Duration 1313 seconds

==> ./tests/test_62510/logs/maxtable62510.testcase <==
14:31:19> Created table t953
14:31:28> Created table t954
Duration 2444 seconds

==> ./tests/test_62510/logs/ixentryorder62510.testcase <==
15:17:48> (out='successfully deleted files')
15:18:25> done with run 19
Duration 1209 seconds

==> ./tests/test_62510/logs/incrementalbackupusenames62510.testcase <==
14:56:43> x incrementalbackupusenames62510.txn/log.0000000015 FULL size=41942956 pagesize=4096 not sparse 
14:56:45> x incrementalbackupusenames62510.txn/log.0000000016 FULL size=41941104 pagesize=4096 not sparse 
Duration 1837 seconds

==> ./tests/test_62510/logs/odhblobs62510.testcase <==
14:26:47> 1
14:26:47> [INSERT INTO self VALUES(x'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF')] rc 0
Duration 94 seconds

==> ./tests/test_62510/logs/dohsqlleaks62510.testcase <==
15:19:23>  total     /             |        51105792     100%         46822384          4283408         51388416
15:19:23> ------------------------------------------------------------------------------------------------------
Duration 1280 seconds

==> ./tests/test_62510/logs/incrementalbackup62510.testcase <==
14:57:43> + set -x
14:57:43> + /PATH/comdb2/build/tools/cdb2sql/cdb2sql --cdb2cfg /PATH/comdb2/tests/test_62510/incrementalbackup62510/comdb2db.cfg incrementalbackup62510 default 'insert into load (id, name, data) values(1, '\''xxx'\'', x'\''1234'\'')'
Duration 1863 seconds

==> ./tests/test_62510/logs/sirandtest62510.testcase <==
15:01:57> ERROR: Cancelling test
15:01:57> Testcase failed.
Duration 1248 seconds

==> ./tests/test_62510/logs/cldeadlock62510.testcase <==
14:19:21> [cldeadlock-0] Orphan target is 4653
14:19:21> [cldeadlock-0] Connected to host 'karotte'
Duration 3058 seconds

==> ./tests/test_62510/logs/selectvdeadlock62510.testcase <==
15:35:10> Number of deadlocks: 0, elapsed-time: 671 seconds
15:35:10> Success
Duration 694 seconds

==> ./tests/test_62510/logs/scinsertslogicalscgenerated62510.testcase <==
15:37:22> Inserting 100 records.
15:37:24> Done with rebuild iteration 0
15:37:24> Running verify

==> ./tests/test_62510/logs/sicountbug62510.testcase <==
14:55:01> Snapisol passed
14:55:01> + exit 0
Duration 820 seconds

==> ./tests/test_62510/logs/truncatescofflinegenerated62510.testcase <==
14:08:06> [bulk_rebuild] Truncating to t1 with cstring
14:08:06> [truncate_log] Truncating to {2:19883050}
Duration 2501 seconds

==> ./tests/test_62510/logs/sirace62510.testcase <==
13:53:03> + echo 'Success!'
13:53:03> Success!
Duration 1443 seconds

==> ./tests/test_62510/logs/scindex62510.testcase <==
15:09:46> rm: cannot remove '/home/dan/d/comdb2/tests/test_62510/tmp/cdb2tst_*455655*': No such file or directory
15:09:46> + exit 0
Duration 794 seconds

==> ./tests/test_62510/logs/incrementalbackupload62510.testcase <==
14:25:33> Test Successful
14:25:33> + exit 0
Duration 1952 seconds

==> ./tests/test_62510/logs/updaterlatency62510.testcase <==
15:17:45> + echo Success
15:17:45> Success
Duration 446 seconds

**Comment by mponomar** [comment]
`make` in `tests/` does log in a consistent matter.  The testcase files are really there for humans to look at what may have gone wrong with a test - we don't parse those.

https://github.com/bloomberg/comdb2/blob/master/contrib/dev-util/testrunner.c for an example of something that parses the output (look for output lines that start with '!')

**Comment by danshearer** [comment]
Thanks that helps. I'll see if I can put something in the docs to make that more obvious. 

Happy to close.
