### ISSUE TITLE
Update JDK version to 1.8

### ISSUE THREAD

**Issue by hgeraldino** [bloomberg/comdb2#2642]
Is it possible to have the JDK version updated to at least 1.8 (or, preferably, use Java 11) on the cdb2jdbc project? 

JDK 1.6 is not just really old, but is no longer supported by Oracle (or any other JVM vendor).

**Comment by riverszhang89** [comment]
We do not specify a JDK version. You are free to use JDK 8 or 11 to build the driver. In the POM file, we do tell javac that `-source` and `-target` are 1.6, to support at least JRE 1.6. The driver works fine in any 1.6+ JREs.
