### ISSUE TITLE
Upstream SQLite source transformation using GCC Plugin

### ISSUE THREAD

**Issue by decalek** [bloomberg/comdb2#3058]
Many databases maintain SQLite forks (dbdb-q1)[https://dbdb.io/browse?embeds=sqlite] (dbdb-q2)[https://dbdb.io/browse?derived=sqlite]. Might be not so coincidentally, the biggest two (both as codebase and userbase) has Lua SPs ;-).

BTW, dbdb.io data is not accurate (e.g. [comdb2](https://dbdb.io/db/comdb2) profile is just a stub) and exhaustive - other valuable forks e.g. the versioned db [litetree](https://github.com/aergoio/litetree), which is also at 3.27.2, are completly missing in this catalog (IMHO dbdb catalog would be more maintainable and useful as a [dolt database](https://www.dolthub.com/discover) trhough pull requests by the db community, but that is another story).

I am curious about your experience and opinion: How hard is that maintenance at BLP? Do you have plans of "bulk" import of some future sqlite version (beside the cherry-picks)? What is your opinion on a eventual [compiler plugin](https://peter.colberg.org/gcc-lua) based framework for querying and transformation of the SQLite sources according to the rules of given initial, manual fork? Do you think that other vendors would participate once such eventual framework have been bootstrapped?

IMHO, At some stage, such initiative might be beneficial not only for the SQLite embedders but for the upstream too - e.g. more flexibility and accuracy with eventual big refactorings, alternative of current text based source preprocessing at buildtime, etc.. Unfortunately, there are not yet TCL GCC plugin API bindings, Richard will be disappointed a little ;-).

Another more general positive outcome would be, that once applied in relatively sophisticated task like SQLite sources adaptation, and if implemented in sufficiently declarative fashion (e.g. why not in Lua/[Fennel](https://fennel-lang.org/) + SQL), the fork bundling of other popular libraries, which imposes problems against the rules of many Linux distributions could be streamlined too (ideally trough possibility of generating definitions for already established tools like [coccinelle](https://gitlab.inria.fr/coccinelle))

**Comment by mponomar** [comment]
We pull new SQLite versions for major releases.  There's quite a few diffs between our source tree and SQLite's, and for the time being we've been applying them manually (well, at least resolving conflicts manually).  It's not as problematic as you imagine.  I'm sure there's better automated ways to do this, but frankly it's not enough of a hardship for us to explore them just yet.
