### ISSUE TITLE
How to have cdb2_stat, cdb2_printlog installed in contrib/docker/build after 'make docker-cluster'?

### ISSUE THREAD

**Issue by AnDongLi** [bloomberg/comdb2#364]
Currently after I run make docker-cluster, these two executables are not installed under contrib/docker/build/opt/bb/bin, so they are not installed in the cluster nodes.
How to have them generated?

**Comment by riverszhang89** [comment]
Thank you for finding the bug.

**Comment by AnDongLi** [comment]
I'm glad to be helpful.
