### ISSUE TITLE
How does cdb2 wrap berkdb real table to provide different level of isolation?

### ISSUE THREAD

**Issue by AnDongLi** [bloomberg/comdb2#373]
I searched the source code and found some structs in sqliteInt.h(VTable, Table, sqlite3_vtab),
also those structs(subclass of sqlite3_vtab_*) in modules under sqlite/ext/comdb2 are interesting.

Could you explain a bit how cdb2 laye encapsulate berkdb and enhance with temp datas to provide richer features?

Also, is there two dirfferent type of transaction in cdb2 layer and in berkdb layer?

**Comment by markhannum** [comment]
We replace sqlite's btree layer (see db/sqlglue.c) with our own back-end.  Reads are handled directly on the replicant by accessing local berkley btrees.  Writes are shipped to the master as low-level record-at-a-time commands.  There is a single model for transaction isolation in comdb2 (not two).  Much of the work for implementing comdb2's isolation is done by virtue of a transaction's "shadow-tables".  You can think of a shadow-table as containing the logical difference between the current btree and the btree as it was at the beginning of the transaction.  As a concrete example, if a snapshot-isolation client begins a transaction (t1) and a record is subsequently deleted from the database by a different transaction, a copy of the deleted record is saved in t1's shadow table, and a cursor belonging to t1 which accesses this part of the btree will see the record.

You can study this logic in the "cursor-layer", largely implemented in bdb/cursor.c, bdb/cursor_ll.c, bdb/bdb_osqllog.c and bdb/bdb_osqltrn.c.  bdb_cursor_move_merge implements the merging of the database's btree and a transaction's shadow-tables for snapshot isolation.  If a cursor reads a btree and discovers that there have been changes, the code reconstructs any missing or changed records from the berkley log files and adds them to the transaction's shadow tables.  This code is in flux right now, but bdb_osql_update_shadows shows "old" snapshot updating a transaction's shadow-tables, while bdb_cursor_update_shadows_with_pglogs shows "new" snapshot adding changes that occurred on the page that the cursor has just moved to.

**Comment by dorinhogea** [comment]
If you look at the server code, you will see at least two types of transactions, indeed. During sql processing, the cluster has one "logical" transaction, which stores the intermediate results, shadow tables on the replicants, bplog on the master .  This transaction is OCC, only relying on temporary read locks and row versioning to handle contention, so it is non-blocking versus other OCC transactions. 
Once the commit is triggered on the replicant, a second transaction is started on the master, which processes the bplog.   This transaction is NOT OCC, instead it relies on pessimist locks to implement ACID semantics.  The versioning provided by the bplog allows us to protect against various r-w and w-w conflicts.   Higher isolation transaction mode have more checks and lower tolerance to contention, versus non-serializable transactions, which trade poorer user semantics for higher throughput.
There is a third type of transaction, called also logical, which is used by rowlocks.   It is sharing the same properties with replicant sql transaction (first described category) with respect to locking and relationship with berkeley db.

**Comment by AnDongLi** [comment]
@markhannum, the reply is very helpful, could you explain a bit more about 'old snapshot' and 'new snapshot', maybe with some examples?

**Comment by ldennis** [comment]
Both 'old' and 'new' snapshot implement the idea @markhannum mentioned earlier --
> If a cursor reads a btree and discovers that there have been changes, the code reconstructs any missing or changed records from the berkley log files and adds them to the transaction's shadow tables.

'new' snapshot is an optimization for our previous snapshot implementation. In the 'old' snapshot implementation, the code reconstructs all changed records regardless whether the transaction has to read them. 'new' snapshot reconstructs records in an "on-demand" manner. An example would be: if 10 records locating in 10 different pages have been changed since your snapshot start time and your snapshot does a range select which is only interested in 2 of them, 'old' snapshot reconstructs all 10 changed rows regardless whereas 'new' snapshot will only reconstruct the 2 you need.

As Mark pointed out, the code is in flux at this moment. For a bit more info, see #361 .
