### ISSUE TITLE
What triggers data files creation?

### ISSUE THREAD

**Issue by AnDongLi** [bloomberg/comdb2#392]
Here are the files under my db home:
comdb2_llmeta.dta
comdb2_metadata.dta
file_vers_map
logs(dir)
numbers_59a263bf00050000.datas0
numbers_59a263bf00050000.datas1
numbers_59a263bf00050000.datas2
numbers_59a263bf00050000.datas3
numbers_59a263bf00050000.datas4
numbers_59a263bf00050000.datas5
numbers_59a263bf00050000.datas6
numbers_59a263bf00050000.datas7
numbers_59a263bf00060000.index
numbers_59bbbcb000050000.datas0
numbers_59bbbcb000050000.datas1
numbers_59bbbcb000050000.datas2
numbers_59bbbcb000050000.datas3
numbers_59bbbcb000050000.datas4
numbers_59bbbcb000050000.datas5
numbers_59bbbcb000050000.datas6
numbers_59bbbcb000050000.datas7
numbers_59bbbcb000060000.index
sqlite_stat4_59bbbc4a00030000.datas0
sqlite_stat4_59bbbc4a00030000.datas1
sqlite_stat4_59bbbc4a00030000.datas2
sqlite_stat4_59bbbc4a00030000.datas3
sqlite_stat4_59bbbc4a00030000.datas4
sqlite_stat4_59bbbc4a00030000.datas5
sqlite_stat4_59bbbc4a00030000.datas6
sqlite_stat4_59bbbc4a00030000.datas7
sqlite_stat4_59bbbc4a00040000.index
testdb.lrl
testdb.lrl.sav
testdb.service
tmp(dir)

I created a table called numbers,  and I see each file's size is 8K, 
What's the meaning of 59a263bf00050000 in the filename numbers_59a263bf00050000.datas0?
What condition make system create a file with new prefix like numbers_59bbbcb000050000?

Same question to the files begin with sqlite_stat.

**Comment by akshatsikarwar** [comment]
These are created any time you create a table. `datas0-7` are stripes. See section 4.3.1 for detail in the Comdb2 paper.

> In practice, data files are split into multiple B-trees (typically eight) which we refer to as stripes. This alleviates a concurrency hotspot when writing to the right side of the B-tree. In order to o↵er a uniform view of the storage, cdb2 implements its own abstraction of a tree, allowing it to transparently merge underlying B-tree structures.

**Comment by akshatsikarwar** [comment]
sqlite_stat* files are for tables which stores data gathered by `analyze`
