### ISSUE TITLE
Missing folder Sqlquery and Sqlresponse under com.bloomberg.comdb2.jdbc

### ISSUE THREAD

**Issue by AnDongLi** [bloomberg/comdb2#405]
Folder Cdb2Types  and classes under it are also missing under com.bloomberg.system.comdb2.jdbc.

**Comment by AnDongLi** [comment]
Just checked the latest version source code, there is a testcase called createTable(). I guess this will make failing testcases pass.

**Comment by AnDongLi** [comment]
OK, I found Sqlquery.java and Sqlresponse.java are generated source and they are under cdb2jdbc/target/generated-sources, so I have to copy them to the maven project source dirrectory.

But classes under Cdb2Types are still missing.

**Comment by AnDongLi** [comment]
So Cdb2Types exists but in com.bloomberg.comdb2.jdbc rather than com.bloomberg.system.comdb2.jdbc.
The class com.bloomberg.system.comdb2.jdbc.Testcases is using wrong package name  and it tries to access private field of Cdb2Types.Datetime.

**Comment by riverszhang89** [comment]
The file you're looking at is deprecated. Please check out JUnit tests at https://github.com/bloomberg/comdb2/tree/master/cdb2jdbc/src/test/java/com/bloomberg/comdb2/jdbc.
