### ISSUE TITLE
what's "tag ondisk" in csc file?

### ISSUE THREAD

**Issue by AnDongLi** [bloomberg/comdb2#408]
I saw some definitions begin with "tag" in tests folder, and I cound't find the explanation about it,
could you help to make it clear? maybe add some section to the document page.
 
tag ondisk {
    cstring tbl[64]
    cstring idx[64] null=yes
    cstring stat[4096]
}

tag "stat1" {
    cstring tbl[64]
    cstring idx[64]
    cstring stat[4096]
}

keys {
    "0" = tbl + idx
}

tag "default" {
    cstring tbl[64]
    cstring idx[64]
    cstring stat[4096]
}

**Comment by riverszhang89** [comment]
It is our own schema definition language, called `csc2`. The `ondisk` tag, as the name indicates, defines the physical structure of the table. Other tags each define a projection of the `ondisk` tag. You can find more information about `csc2` [here](https://bloomberg.github.io/comdb2/table_schema.html). However, it is strongly encouraged to use DDL instead.

**Comment by AnDongLi** [comment]
Yes, I read that document; there are two tags used in create table but there is no explaination about what's the purpose to use tag and how to define a tag.

**Comment by AnDongLi** [comment]
Is the tag ondisk telling comdb2 that the fields of the table need to be stored on disk by strictly following the order in the tag definition?

**Comment by riverszhang89** [comment]
Yes, except for blob and vutf8 types - they are stored in auxiliary b-trees.

**Comment by AnDongLi** [comment]
I see. thanks.

**Comment by riverszhang89** [comment]
Thank you.

**Comment by AnDongLi** [comment]
What kind of requirement ask for this? From the tests that use it I can't get a clue.

**Comment by riverszhang89** [comment]
We implemented it this way.

**Comment by AnDongLi** [comment]
OK, so now 'tag ondisk {...}' can always be replaced  with 'schema { ... }', right?

**Comment by riverszhang89** [comment]
You're right. However if you're writing up an application with comdb2 as a backend, you are encouraged to use DDL instead.
