### ISSUE TITLE
Deadlock between schema lock and table locks on the master node

### ISSUE THREAD

**Issue by dorinhogea** [bloomberg/comdb2#418]
Schema lock and table locks are acquired in both orders; 
1) when a new sql statement is prepared, schema lock is acquired first, followed by table locks accessed in the statement;
2) A bplog transaction would acquire table locks first, and, in the following conditions requires a schema lock afterwards:
 2.1) table has index on expressions,
 2.2)  a schema change is concurrent for that table
In this context, the master doesn't receive keys for index on expressions, and it needs to generate them on the fly by running sql statements. Preparing the statements requires the schema lock, which happens after the table locks are obtained.
Possible solution:
- deadlock the transaction that needs to prepare an sql statement in the case (2), and during retry, acquire schema lock early (i.e. before getting table locks)

**Comment by akshatsikarwar** [comment]
We can create SQLite VMs, one per blockproc. These will never need to check schema or stats. Can bootstrap it with zero tables. This way will never require schema lk.

**Comment by ldennis** [comment]
#443
