### ISSUE TITLE
cdb2_run_statement_typed with an empty types array behaves like cdb2_run_statement

### ISSUE THREAD

**Issue by godlygeek** [bloomberg/comdb2#4389]
**Describe the bug**
This doesn't appear to be documented anywhere, and I'm not convinced that it's intended behavior:

If `cdb2_run_statement_typed` is called with `nparms` set to 0, it behaves as though `cdb2_run_statement` was called.

**Expected behavior**

I expected this to instead fail if a result set is returned. This came up while adding support for `cdb2_run_statement_typed` to python-comdb2 (https://github.com/bloomberg/python-comdb2/pull/66) - I added a test where I ran `select 1` with an empty types array, and to my surprise it succeeded instead of failing.

That runs contrary to the behavior I was documenting:

```
        If ``column_types`` is provided, it must be a sequence of members of
        the `ColumnType` enumeration. The database will coerce the data in the
        Nth column of the result set to the Nth given column type. An error
        will be raised if the number of elements in ``column_types`` doesn't
        match the number of columns in the result set, or if one of the
        elements is not a supported column type, or if coercion fails.
```

Is it intentional that an empty array is treated as though no types were passed at all? Should I accept that, and document that as a special case?

**Comment by mponomar** [comment]
Yes, this is intentional.  cdb2_run_statement calls cdb2_run_statement_typed with 0 columns.  I believe it if you tell me we didn't document it well.
