### ISSUE TITLE
CDB2JDBC Update returning extra row

### ISSUE THREAD

**Issue by saatviks** [bloomberg/comdb2#557]
The `cdb2jdbc` JDBC connector has the method `executeUpdate` which seems to return 2, when 1 row is updated. Is this the expected behaviour?
The documentation says that it should return the number of rows affected [link](https://bloomberg.github.io/comdb2/jdbc_api.html#performing-updates).

**Comment by riverszhang89** [comment]
The function, by default, returns the number of rows updated by the transaction. To make it return per-query effects, you'd use `statement_query_effects` URL parameter. Your JDBC connection string would then look like this:

```
jdbc:comdb2//<hostname>/<database>?statement_query_effects=1
```

**Comment by saatviks** [comment]
Thanks that resolved it.
