### ISSUE TITLE
Not able to create database using the latest commits

### ISSUE THREAD

**Issue by Blade-Lee** [bloomberg/comdb2#571]
Hello, I'm trying to build up comdb2 and create a database on my Linux machine. However, I met `[ERROR] goodbye` when I use `comdb2 --create testdb`. Below is my workflow:

1. get into home directory
2. `git clone https://github.com/bloomberg/comdb2`
3. `sudo apt-get install -y build-essential cmake bison flex libprotobuf-c-dev libreadline-dev libsqlite3-dev libssl-dev libunwind-dev libz1 libz-dev make gawk protobuf-c-compiler uuid-dev liblz4-tool liblz4-dev libprotobuf-c1 libsqlite3-0 libuuid1 libz1 tzdata ncurses-dev tcl bc`
4. `cd comdb2`
5. `mkdir build && cd build`
6. `cmake -DCMAKE_INSTALL_PREFIX=$HOME/comdb2 ..`
7. `make -j8`
8. `sudo USER=${whoami} make install`
9. `export PATH=$PATH:$HOME/comdb2/bin`
10. `sudo chmod -R 777 $HOME/comdb2`
11. `pmux -n`
12. `comdb2 --create testdb &`
13. Then I met a`[ERROR] goodbye` message.

However, if I change to commit 4988b68, and redo step 1~12, the database can be created successfully.

Could please help to figure out what is wrong?

**Comment by riverszhang89** [comment]
Thank you for reporting the bug. This is not a real error - the `goodbye` message was set to a wrong log level in https://github.com/bloomberg/comdb2/commit/110de79c1401449db057210c3d85075e1bed4620. I'm sorry about the confusion.

**Comment by akshatsikarwar** [comment]
Also addressed in pull req earlier in the day https://github.com/bloomberg/comdb2/pull/570
