### ISSUE TITLE
Is `RETURNING` supported in Comdb2?

### ISSUE THREAD

**Issue by Blade-Lee** [bloomberg/comdb2#588]
Hello, currently I'm using a table below:

```
CREATE TABLE text (
  old_id int NOT NULL,
  old_text text NOT NULL,
  old_flags varchar(255) NOT NULL,
  old_page int DEFAULT '0',
  PRIMARY KEY (old_id)
);
```

and I'd like to use `INSERT INTO text (old_page,old_text,old_flags) VALUES (?,?,?) RETURNING old_id` to get back the key of the newly inserted tuple, thus I'm trying to use `RETURNING` here. May I ask is `RETURNING` supported? If not, how can I get back the `old_id` of the newly inserted tuple?

**Comment by akshatsikarwar** [comment]
Comdb2 doesn't really have notion of a primary key. `PRIMARY KEY (old_id)` is just syntactic sugar for creating a unique not null key on `old_id`. This stmt will fail: `INSERT INTO text (old_page,old_text,old_flags) VALUES (?,?,?)`. You need to provide value to insert and that makes `RETURNING` redundant. Its whatever you tried to insert.

Comdb2 schemas are specified using CSC2 (even when using vanilla SQL DDL; its translated to nearest CSC2) https://bloomberg.github.io/comdb2/table_schema.html

**Comment by mponomar** [comment]
It's not supported.  It's less useful in Comdb2 than it would be in PostgreSQL since we don't (yet) support sequences or autoincrement keys, so the only value old_id can be is the value provided in the insert statement (or NULL, or the default value, but in either case provided by the application).

**Comment by Blade-Lee** [comment]
Thanks for the reply, it's my mistake in the statement `INSERT INTO text (old_page,old_text,old_flags) VALUES (?,?,?) RETURNING old_id`, yes I will be inserting values instead of `?`.
