### ISSUE TITLE
OSX: clang compilation error: `use of undeclared identifier 'PATH_MAX'`

### ISSUE THREAD

**Issue by mheiber** [bloomberg/comdb2#622]
## Description

clang compilation error on OSX: `use of undeclared identifier 'PATH_MAX'`

## Steps to Reproduce

- Using a mac (tested on OSX High Sierra 10.12.2), follow the installation instructions in README. 
- The error happens when running `make install` in the `build` directory

```
/Users/maxwellheiber/dev/comdb2/berkdb/mp/mp_bh.c:578:11: error: use of undeclared identifier 'PATH_MAX'
        char dir[PATH_MAX];
                 ^
1 error generated.
make[2]: *** [berkdb/CMakeFiles/db.dir/mp/mp_bh.c.o] Error 1
make[1]: *** [berkdb/CMakeFiles/db.dir/all] Error 2
make: *** [all] Error 2
```

Versions:

```
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.3.0
```

comdb2 compiles and runs if a definition for `PATH_MAX` is added to the top of the file.

**Comment by riverszhang89** [comment]
Thank you very much for reporting the issue!
