### ISSUE TITLE
raw read/write performance expectation on a single node comdb2

### ISSUE THREAD

**Issue by 50hz** [bloomberg/comdb2#854]
hi there, hopefully, this question does not look too naive. 

What kind of performance superiority should I expect from comdb2, comparing to a more typical RMDBS like SQL server on raw read/write speed on row-oriented data?  

or is there some specific use case that comdb2 will outperform most of the alternatives?

**Comment by mponomar** [comment]
A typical install of Comdb2 runs with synchronous replication on a cluster of several nodes.  The raw write rate is dictated by the slowest link between nodes.   You can increase write throughput by batching more work into a transaction (or by doing more transactions in parallel).  You can increase read throughput by adding mode nodes to the cluster.   I wouldn't expect Comdb2 to win any serial speed contests on a single node, yet.  It's really not the intended uses case.

**Comment by 50hz** [comment]
@mponomar thanks for the hints. I think I was trying to work out what can be a good motivation to use comdb2 instead of other alternatives, apart from the admiration of Bloomberg technology :) what are the key strengths of comdb2?

**Comment by mponomar** [comment]
Easy clustering/synchronous replication (ie: update once, new value everywhere).  Good availability in face of machine/network issues (ie: reliable).  Ease of setup.   Easy to scale up reads.

**Comment by 50hz** [comment]
that all make sense, thanks!
