### ISSUE TITLE
Inquiry: Is there an official release for the project?

### ISSUE THREAD

**Issue by EricHripko** [bloomberg/comdb2#997]
I'm creating a [Homebrew](https://brew.sh/) formula for comdb2 and it seems like the current version is 7.0pre. Is there's an official stable(ish) release that should be installed as opposed to taking latest?

**Comment by mponomar** [comment]
Not yet.  We're going to tag releases.  The latest tag will be the most stable release.

**Comment by EricHripko** [comment]
Awesome - thank you for getting back to me. Have a lovely day!
